### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by vedantk21** [tanaypratap/gradiot#14]
PFA a typo error:
It should be 'Gradiot' and not 'Gradient'
(3rd line, last word)
Regards

![Screenshot_20200424-123142](https://user-images.githubusercontent.com/62688566/80184536-63d5ef00-8628-11ea-9cb1-83984d396b6b.jpg)

**Comment by gkanishk** [comment]
Thanks for raising the issue, resolved!
