### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by vedantk21** [tanaypratap/gradiot#19]
Please change logo of 'Dribbble' to 'Instagram' as it redirects to an Instagram account
![Screenshot_20200503-100120](https://user-images.githubusercontent.com/62688566/80898784-42aa8800-8d25-11ea-825f-f39ce83f65d5.jpg)

**Comment by gkanishk** [comment]
Hey @vedantk21 ,
So nice of you giving feedback but that's the old preview you can see the latest build at https://gradiot.club/ that hass all the fixes.
